[package]
authors = ["Albert Hermida <albert@switchboard.xyz>"]
name = "OnDemand"
version = "1.0.0"

[addresses]
on_demand = "_"
std = "0x1"

[dev-addresses]
on_demand = '0x55'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-stdlib"}
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/move-stdlib"}